### PR TITLE
Integrate devise with the user model

### PR DESCRIPTION
**Pull request by Peter1907**
Hello, dear code reviewer!

In this branch, I've implemented the following:
- Added "devise" to the Gemfile
- Configured the application record to use "devise"
- Reconfigured the  schema file to include emails & passwords

I'm working solo this week, that's why all the commits are mine.
Screenshot 2023-01-06 at 13-47-44 Dashboard

email_screenshot

Let me know if there's anything to be modified ... I'm not 100% following everything here so please mention anything that I need to know more in-depth, maybe some resources to check, or some clarification.
Thank you so much for your time!

### CODE REVIEW

**Comment by DammyShittu** [comment]
Hi @Peter1907,

While you made a great effort in this project, I cannot proceed to review your code.

## Invalid Code Review Request

### Kindly ensure your coding partner contributes to this project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Peter1907** [comment]
@DammyShittu I mentioned in the description that I'm working solo this week (I don't have a partner to commit something)

**Comment by codecaiine** [comment]
@Peter1907 Please Include in your PR description a screenshot that proved that you are working solo this week. :smiley:

**Review by codecaiine — COMMENTED** [review]
Hi @Peter1907 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is a pair programming activity but I can't find your partner contribution. Please reach out to the student success team if you haven't done it yet and/or add a screenshot that proves that you are working solo this week. in your PR description  :+1: 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by sumairq — APPROVED** [review]
### Hi @Peter1907 , 



Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Good commit history
✔️Linters are passing
✔️Very professional README
✔️Correct Git flow
✔️Descriptive PR
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
